version: '3.4'

services:
  blazorapp3:
    image: ${DOCKER_REGISTRY-}blazorapp3
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: BlazorApp3/Dockerfile
    ports:
        - "8000:80"
    environment:
      DB_CONNECTION_STRING: "Host=postgres_image;Port=5432;Database=dockerDB;Username=postgres;Password=q65nCN"
    

  postgres_image:
    image: postgres
    volumes:
      - database-data:/var/lib/postgresql/data
      - ./dump.sql:/dump.sql
    environment:
      - POSTGRES_DB=dockerDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=q65nCN
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
    - PGADMIN_DEFAULT_EMAIL=admin@admin.com
    - PGADMIN_DEFAULT_PASSWORD=root
    ports:
       - "5050:80"

volumes:
    blazorapp3:
    pgadmin:
    database-data:
    
